[project]
name = "break"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lamsiddharth", email = "siddharthpradhan2004@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pymongo>=4.17.0",
    "requests>=2.34.2",
]

[project.scripts]
break = "break:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
